INCLUDE 'EMU8086.INC' 
.STACK 100H
.DATA
.CODE
MAIN PROC 
     

    MOV BX,10
    
    CMP BX,100
    JGE CASE1
    
    CMP BX,80
    JGE CASE2
    
    CMP BX,60
    JGE CASE3
    
    CMP BX,40
    JGE CASE4
    
    CMP BX,20
    JGE CASE5
    
    JMP DEFAULT
    
    CASE1:
    PRINTN "THE NUMBER IS GREATER THEN OR EQUAL 100"
    JMP BREAK
    
    CASE2:
    PRINTN "THE NUMBER IS GREATER OR EQUAL 80"
    JMP BREAK
    
    CASE3:
    PRINTN "THE NUMBER IS GREATER OR EQUAL 60"
    JMP BREAK
    
    CASE4:
    PRINTN "THE NUMBER IS GREATER OR EQUAL 40"
    JMP BREAK
    
    CASE5:
    PRINTN "THE NUMBER IS GREATER OR EQUAL 20"
    JMP BREAK
    
    DEFAULT:
    PRINTN "THE NUMBER IS LESS THEN 20"
    
    BREAK:
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN




