INCLUDE "EMU8086.INC"
.MODEL SMALL
.DATA
    MSG1 DB "ENTER THE FIRST NUMBER : $"
    MSG2 DB "ENTER THE SECOND NUMBER: $"
    MSG3 DB "ENTER THE THIRD NUMBER: $" 
    MSG_EQ DB "EQUIVALENT$"
    MSG_ISO DB "OSCALES$"
    MSG_SCAL DB "SCALAR$"
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    LEA DX, MSG1
    MOV AH, 9
    INT 21H
    MOV AH, 1
    INT 21H
    SUB AL, '0'
    MOV BL, AL
    PRINTN ""

    LEA DX, MSG2
    MOV AH, 9
    INT 21H
    MOV AH, 1
    INT 21H
    SUB AL, '0'
    MOV BH, AL
    PRINTN ""

    LEA DX, MSG3
    MOV AH, 9
    INT 21H
    MOV AH, 1
    INT 21H
    SUB AL, '0'
    MOV CL, AL
    PRINTN ""

    CMP BL, BH
    JNE CHECK_ISOSCELES
    CMP BL, CL
    JNE CHECK_ISOSCELES
    LEA DX, MSG_EQ
    JMP DISPLAY_MSG

CHECK_ISOSCELES:
    CMP BL, BH
    JE ISOSCELES
    CMP BL, CL
    JE ISOSCELES
    CMP BH, CL
    JE ISOSCELES
    LEA DX, MSG_SCAL
    JMP DISPLAY_MSG

ISOSCELES:
    LEA DX, MSG_ISO

DISPLAY_MSG:
    MOV AH, 9
    INT 21H
    PRINTN ""

EXIT:
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN
